### ISSUE TITLE
Creating custom ROS2 interfaces

### ISSUE THREAD

**Issue by holmbuar** [micro-ROS/micro_ros_raspberrypi_pico_sdk#945]
I want to create a custom service in my environment. 

@pablogs9 has previously linked to this [tutorial](https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/custom_types/custom_types.html)

which is depending on [setting up a Micro-ROS workspace](https://docs.vulcanexus.org/en/humble/rst/microros_documentation/getting_started/getting_started.html)

Do I have to install Vulcanexus, and create a micro ROS workspace? In an old issue, Pablo replied this:  https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/issues/83#issuecomment-847568777_

Does this recipe still hold? The `microros_static_library/library_generation/extra_packages` folder is already in my environment, and the correct tag seem to be in [Docker hub](https://hub.docker.com/layers/microros/micro_ros_static_library_builder/humble/images/sha256-a2521a9bb5fe5a4d7ea3a08cb1ebb960629a280a6e60cb1c576015962865ee47?context=explore)

**Comment by holmbuar** [comment]
I just tried running the Docker command

```
docker run -it -v $(pwd):/project --net=host microros/micro_ros_static_library_builder:humble
```
after pasting in a `custom_interfaces` package I made in another ROS2 workspace, to `microros_static_library/library_generation/extra_packages/`. The procedure fails

```
CMake Error at /uros_ws/firmware/mcu_ws/install/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  custom_interfaces --arguments-file
  /uros_ws/firmware/mcu_ws/build/custom_interfaces/rosidl_adapter__arguments__custom_interfaces.json
  --output-dir
  /uros_ws/firmware/mcu_ws/build/custom_interfaces/rosidl_adapter/custom_interfaces
  --output-file
  /uros_ws/firmware/mcu_ws/build/custom_interfaces/rosidl_adapter/custom_interfaces.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/uros_ws/firmware/mcu_ws/install/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/uros_ws/firmware/mcu_ws/install/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/uros_ws/firmware/mcu_ws/install/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
      return convert_srv_to_idl(
    File "/uros_ws/firmware/mcu_ws/install/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
      srv = parse_service_string(package_name, input_file.stem, content)
    File "/uros_ws/firmware/mcu_ws/install/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 850, in parse_service_string
      raise InvalidServiceSpecification(

  rosidl_adapter.parser.InvalidServiceSpecification: Could not find separator
  '---' between request and response

Call Stack (most recent call first):
  /uros_ws/firmware/mcu_ws/install/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:28 (rosidl_generate_interfaces)
```

after **deleting** the `CMakeLists.txt` files in my `src` subfolders!

I can see my `custom_interfaces` service type added to the `available_ros_2_types` though.

NOTE: I have not made a micro ROS workspace, I ran the command inside my now heavily customized fork of the micro ROS repo...

**Comment by holmbuar** [comment]
Here is my `package.xml` file inside the `custom_interfaces` directory

```
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>custom_interfaces</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="me@example.com">ME</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
```

and CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.8)
project(custom_interfaces)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
# uncomment the following section in order to fill in
# further dependencies manually.
# find_package(<dependency> REQUIRED)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

find_package(rosidl_default_generators REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "srv/MotorData.srv"
 )

ament_package()
```

**Comment by holmbuar** [comment]
I also cloned a fresh mROS SDK repo, pasted custom folder in extra packages folder; ran Docker command from project root. Same result, some more errors:

```
CMake Warning at /uros_ws/firmware/mcu_ws/install/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'rcutils' exports library 'dl' which couldn't be found
Call Stack (most recent call first):
  /uros_ws/firmware/mcu_ws/install/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_runtime_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_runtime_c/cmake/rosidl_runtime_cConfig.cmake:41 (include)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_typesupport_introspection_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_typesupport_introspection_c/cmake/rosidl_typesupport_introspection_cConfig.cmake:41 (include)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:13 (find_package)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_default_generators/cmake/rosidl_default_generators-extras.cmake:21 (find_package)
  /uros_ws/firmware/mcu_ws/install/share/rosidl_default_generators/cmake/rosidl_default_generatorsConfig.cmake:41 (include)
  CMakeLists.txt:26 (find_package)

```

```
rsync: [sender] change_dir "/project/libmicroros/include/action_msgs/action_msgs" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rsync: [sender] change_dir "/project/libmicroros/include/actionlib_msgs/actionlib_msgs" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rsync: [sender] change_dir "/project/libmicroros/include/builtin_interfaces/builtin_interfaces" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rsync: [sender] change_dir "/project/libmicroros/include/common_interfaces/common_interfaces" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rsync: [sender] change_dir "/project/libmicroros/include/composition_interfaces/composition_interfaces" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rsync: [sender] change_dir "/project/libmicroros/include/control_msgs/control_msgs" failed: No such file or directory (2)

```

**Comment by holmbuar** [comment]
My goof. After formatting the `.srv` file [correctly](https://docs.ros.org/en/foxy/Concepts/About-ROS-Interfaces.html#service-description-specification)

```
string send_motor_data
---
float64 velocity
float64 position
```

it works. I guess the error message

```
 rosidl_adapter.parser.InvalidServiceSpecification: Could not find separator
  '---' between request and response
```

was not that unclear after all...

Still there are a lot of `rsync` related messages though, seemingly from using `project/` in the path?

**Comment by holmbuar** [comment]
How to modify the shell script, for only installing extra packages?

**Comment by pablogs9** [comment]
Yes it is possible. 

Closing as solved
